#debug: true
# GraphQL Starter Debug
logginglevel.com.merapar: DEBUG
#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # Required to use db fields with field names and use @Column annotation
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
