# Actuator
# Full authentication is required to access actuator endpoints. Consider adding Spring Security or set 'management.security.enabled' to false.
management:
  security:
    enabled: false
#debug: true
# GraphQL Starter Debug
logginglevel.com.merapar: DEBUG
#server:
#  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        # Required to use db fields with field names and use @Column annotation, else authorId Truens into AUTHOR_ID
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
